# Generated by Django 2.2.24 on 2021-06-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='flag',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
